spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      properties:
        spring:
          json:
            trusted:
              packages: "*"
fint:
  kafka:
    resourceRefreshCron: 0 0 0 */6 * *
    resourceRefreshDuration: 518400000