spring:
  kafka:
    consumer:
      properties:
        spring:
          json:
            trusted:
              packages: "*"
      group-id: testGroupId
    bootstrap-servers: ""
fint:
  org-id: test.org.id
  kafka:
    cache:
      defaultCacheEntryTimeToLiveMillis: 518400000
      defaultCacheHeapSize: 1000000